[package]
authors = ["Wilfried Kopp <wilfried@parity.io>"]
name = "subrpc-core"
version = "0.0.1"
edition = "2021"
description = "subrpc-core is a lib"
homepage = "https://github.com/Wilfried Kopp/subrpc-core"
keywords = ["Wilfried Kopp"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Wilfried Kopp/subrpc-core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
