[package]
authors = ["chevdor <chevdor@gmail.com>"]
name = "subrpc-core"
version = "0.0.1"
edition = "2021"
description = "subrpc-core is a lib"
homepage = "https://github.com/chevdor/subrpc-core"
keywords = ["chevdor"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chevdor/subrpc-core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
