[package]
authors = ["chevdor <chevdor@gmail.com>"]
name = "subrpc-core"
version = "0.0.5"
edition = "2021"
description = "subrpc-core is a lib"
homepage = "https://github.com/chevdor/subrpc"
keywords = ["chevdor"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chevdor/subrpc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
tokio = { version = "1.19", features = ["rt"], default-features = false }
jsonrpsee = { version = "0.19", git = "https://github.com/paritytech/jsonrpsee", features = [
    "client",
] }
anyhow = "1.0"
dirs = "5.0"
chrono = { version = "0.4.23", features = ["serde", "clock"], default-features = false }
reqwest = { version = "0.11.13", features = ["blocking", "json", "default-tls"], default-features = false }
