[package]
authors = ["chevdor <chevdor@gmail.com>"]
name = "subrpc"
version = "0.0.1"
edition = "2021"
description = "subrpc is a cli"
homepage = "https://github.com/chevdor/subrpc"
keywords = ["chevdor"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chevdor/subrpc"

[dependencies]
assert_cmd = "2.0"
env_logger = "0.9"
log = "0.4"
clap = { version = "3.2", features = ["derive", "env", "unicode", "cargo"] }
