[package]
authors = ["Wilfried Kopp <wilfried@parity.io>"]
name = "subrpc"
version = "0.0.0"
edition = "2021"
description = "subrpc is a cli"
homepage = "https://github.com/Wilfried Kopp/subrpc"
keywords = ["Wilfried Kopp"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Wilfried Kopp/subrpc"

[dependencies]
assert_cmd = "2.0"
env_logger = "0.9"
log = "0.4"
clap = { version = "3.2", features = ["derive", "env", "unicode", "cargo"] }
