[package]
authors = ["chevdor <chevdor@gmail.com>"]
name = "subrpc"
version = "0.0.2"
edition = "2021"
description = "subrpc is a cli"
homepage = "https://github.com/chevdor/subrpc"
keywords = ["chevdor"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chevdor/subrpc"

[dependencies]
env_logger = "0.10"
log = "0.4"
clap = { version = "4", features = ["derive", "env", "unicode", "cargo"] }
color-eyre = "0.6.2"
subrpc-core = { path = "../subrpc-core" }

[dev-dependencies]
assert_cmd = "2.0"
